key_bindings:
  - { key: K,        mods: Alt,     chars: "printf \"\\033c\"\n"         }
  - { key: J,        mods: Control|Shift, action: ScrollToBottom         }
  - { key: K,        mods: Control|Shift, action: ScrollToTop            }
    #  - { key: J,        mods: Control, action: ScrollPageDown               }
    #  - { key: K,        mods: Control, action: ScrollPageUp                 }

mouse_bindings:
  - { mouse: Right, action: Paste }
scrolling:
  history: 100000
  multiplier: 10
