[colors.cursor]
cursor = "0x00ff00"
text = "0x000000"

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
WINIT_X11_SCALE_FACTOR = ".85"

[font]
size = 16

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "K", mods = "Alt", chars = " echo -e \"\\033c\"\r" },
  { key = "K", mods = "Command", chars = " echo -e \"\\033c\"\r" },
  { key = "J", mods = "Control|Shift", action = "ScrollLineDown" },
  { key = "K", mods = "Control|Shift", action = "ScrollLineUp" },
  { key = "J", mods = "Control", action = "ScrollPageDown", mode = "~AppCursor|~AppKeypad" },
  { key = "K", mods = "Control", action = "ScrollPageUp", mode = "~AppCursor|~AppKeypad" },
  { key = "A", mode = "Vi|~Search", action = "First" },
  { key = "Semicolon", mode = "Vi|~Search", action = "Last" },
  { key = "Y", mode = "Vi|~Search", action = "Copy" },
  { key = "Up", mods = "Control|Shift", action = "ScrollLineUp" },
  { key = "Down", mods = "Control|Shift", action = "ScrollLineDown" },
  { key = 'T', mods = 'Control|Command', action = 'SpawnNewInstance' },
]

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[scrolling]
history = 100000
multiplier = 10

[terminal.shell]
args = ["--login"]
program = "/bin/bash"

# Remaps option key to alt key in MacOS
[window]
option_as_alt = "Both"
