key_bindings:
  - { key: J,        mods: Alt,     chars: "\x1bj"                       }
  - { key: K,        mods: Alt,     chars: "printf \"\\033c\"\n"         }
  - { key: H,        mods: Alt,     chars: "\x1bh"                       }
